{
  lib,
  buildNpmPackage,
  fetchFromGitHub,
  nix-update-script,
  writableTmpDirAsHomeHook,
  ripgrep,
  fd,
  makeBinaryWrapper,
  stdenvNoCC,
}:
buildNpmPackage (finalAttrs: {
  pname = "pi-coding-agent";
  # Upstream snapshot after the v0.87.1 release: the carried patches target
  # upstream main (the base of PR #10050). Per nixpkgs versioning, a
  # post-release commit is `<latest preceding release>-unstable-<commit date>`.
  version = "0.87.1-unstable-2026-09-25";

  src = fetchFromGitHub {
    owner = "earendil-works";
    repo = "pi";
    # Base revision of PR #10050 (upstream main as of 2026-09-25).
    rev = "d6af72e1857cfb10b41d8ff8e69f0d72b4cf6d31";
    hash = "sha256-K1f4G3rU+Bck80yn7lDP7o/C3mTE+Ucg7qTrC3ulGpQ=";
  };

  # D201 / earendil-works/pi#7319 (+ PR #7324, auto-closed, not merged):
  # OAuth force-refresh + single pre-content 401 retry in Models.stream.
  # Upstream closed the issue with a live-storage read, not an HTTP 401 retry.
  # Drop when a released pi version includes the equivalent retry.
  # Rebased for the 0.87.1-unstable snapshot: `stream`/`streamSimple` bodies now
  # use requireChatProvider, so the shared retry helper matches that shape.
  #
  # earendil-works/pi#10002 (+ PR #10050, open, not merged):
  # Capture non-renderer writes to process.stdout/process.stderr while
  # ProcessTerminal owns the terminal (extension console output no longer
  # garbles the interactive TUI) and surface them through pi-captured-output.log
  # plus a chat entry. This is exactly the PR diff against the pinned revision;
  # drop when a released pi version includes it.
  patches = [
    ./patches/oauth-refresh-on-401.patch
    ./patches/captured-terminal-output.patch
  ];

  npmDepsHash = "sha256-vpxPRiQKGZ3iWi+Bp/vq225mhpk9YAKuxiJxX/FR/m8=";

  # The provider model catalog (packages/ai/src/providers/data/) is generated by
  # a network fetch and is gitignored upstream. Vendored snapshot for the pinned
  # revision: the published @earendil-works/pi-ai npm tarball lags the source
  # (its schema-3 catalog neither type-checks nor contains typesafe.json).
  # To refresh: in a pi checkout at the pinned revision run
  # `npm install --ignore-scripts && npm run hydrate:model-data`, then copy
  # packages/ai/src/providers/data/ over model-data/.
  preConfigure = ''
    mkdir -p packages/ai/src/providers/data
    cp -r ${./model-data}/. packages/ai/src/providers/data
  '';

  npmWorkspace = "packages/coding-agent";

  # Skip native module rebuild for unneeded workspaces (e.g. canvas from web-ui)
  npmRebuildFlags = [ "--ignore-scripts" ];

  nativeBuildInputs = [
    makeBinaryWrapper
  ];

  # Build workspace dependencies in order, then the coding-agent.
  # Invoke tsc directly for workspace deps to skip pi-ai's generate-models
  # script (network); the catalog is supplied via model-data above.
  buildPhase = ''
    runHook preBuild

    npx tsc -p packages/chord/tsconfig.build.json
    npx tsc -p packages/tui/tsconfig.build.json
    npx tsc -p packages/telemetry/tsconfig.build.json
    npx tsc -p packages/ai/tsconfig.build.json
    npx tsc -p packages/agent/tsconfig.build.json
    npx tsc -p packages/protocol/tsconfig.build.json
    npx tsc -p packages/client/tsconfig.build.json
    npx tsc -p packages/server/tsconfig.build.json
    npm run build --workspace=packages/coding-agent

    runHook postBuild
  '';

  dontNpmPrune = true;

  preInstall = ''
    npm prune --omit=dev --no-save
  '';

  # npm workspace symlinks in the output point into packages/ which
  # doesn't exist there. Replace runtime deps with built content and
  # delete the rest.
  postInstall = ''
    local nm="$out/lib/node_modules/pi-monorepo/node_modules"

    # Replace workspace deps needed at runtime with real copies
    for ws in @earendil-works/chord:packages/chord \
              @earendil-works/pi-ai:packages/ai \
              @earendil-works/pi-agent-core:packages/agent \
              @earendil-works/pi-client:packages/client \
              @earendil-works/pi-protocol:packages/protocol \
              @earendil-works/pi-telemetry:packages/telemetry \
              @earendil-works/pi-tui:packages/tui; do
      IFS=: read -r pkg src <<< "$ws"
      rm "$nm/$pkg"
      cp -r "$src" "$nm/$pkg"
    done

    # Delete remaining workspace symlinks
    find "$nm" -type l -lname '*/packages/*' -delete

    # Clean up now-dangling .bin symlinks
    find "$nm/.bin" -xtype l -delete
  ''
  + lib.optionalString stdenvNoCC.hostPlatform.isDarwin ''
    # Remove foreign Linux binaries that make audit-tmpdir try to inspect ELF
    # RPATHs with patchelf
    rm -rf \
      "$nm/@anthropic-ai/sandbox-runtime/dist/vendor/seccomp" \
      "$nm/@anthropic-ai/sandbox-runtime/vendor/seccomp"
  '';

  postFixup = ''
    wrapProgram $out/bin/pi --prefix PATH : ${
      lib.makeBinPath [
        ripgrep
        fd
      ]
    } \
      --set-default PI_SKIP_VERSION_CHECK 1 \
      --set-default PI_TELEMETRY 0
  '';

  doInstallCheck = true;
  nativeInstallCheckInputs = [
    writableTmpDirAsHomeHook
  ];
  # Snapshot pin: pi reports its upstream package.json version, which cannot
  # match the `-unstable-` nix version, so versionCheckHook cannot be used.
  # Smoke-test the binary against the upstream version at the pinned revision.
  installCheckPhase = ''
    runHook preInstallCheck
    test "$("$out/bin/pi" --version)" = "0.87.1"
    runHook postInstallCheck
  '';

  passthru.updateScript = nix-update-script { };

  meta = {
    description = "Coding agent CLI with read, bash, edit, write tools and session management";
    homepage = "https://pi.dev/";
    downloadPage = "https://www.npmjs.com/package/@earendil-works/pi-coding-agent";
    changelog = "https://github.com/earendil-works/pi/blob/v0.87.1/packages/coding-agent/CHANGELOG.md";
    license = lib.licenses.mit;
    maintainers = with lib.maintainers; [ munksgaard ];
    mainProgram = "pi";
  };
})
